baseurl: https://groups.yahoo.com/group/isaiyini
title: 'தனித்தமிழகராதிகளஞ்சியம்'
name: 'தனித்தமிழகராதிகளஞ்சியம்'
email: isaiyini@yahoogroups.com
slogan: 'தேமதுரத் தமிழோசை உலகெலாம் பரவும் வகை செய்வீர்'
permalink: /posts/:year/:month/:day/:title/

menus:
  main:
    - title: 'home'
      href: '/'
    - title: 'posts'
      href: '/posts/'
    - title: 'about'
      href: '/about/'
    - title: 'twitter'
      href: 'http://twitter.com/bjornarneson'
    
    
