baseurl: https://thanithamizhakarathikalanjiyam.github.io/
title: 'தனித்தமிழகராதிக்களஞ்சியம்'
name: 'தனித்தமிழகராதிக்களஞ்சியம்'
email: isaiyini@yahoogroups.com
slogan: 'தேமதுரத் தமிழோசை உலகெலாம் பரவும் வகை செய்வீர்'
permalink: /posts/:year/:month/:day/:title/

menus:
  main:
    - title: 'நுழைவு'
      href: '/'
    - title: 'பதிவுகள்'
      href: '/posts/'
    - title: 'குறிப்படனை'
      href: '/about/'
    - title: 'புதிய சொற்கோவைகள்'
      href: '/definitions/'
    - title: 'பதிவிறக்கம்'
      href: '/downloads/'
    
    

theme: jekyll-theme-modernist